### ISSUE TITLE
Segfault running tetris.

### ISSUE THREAD

**Issue by wornwinter** [wornwinter/DMGe#19]
There's a segfault when Tetris runs.

The following instructions are executed immediately before it happens:
```
[0x29fa] LD A, d8
[0x29fc] LDH (a8), A
[0x29fe] LDH A, (a8)
[0x2a00] LDH A, (a8)
[0x2a02] CPL
[0x2a03] AND d8
[0x2a05] JP Z, a16
```

It seems to happen as soon as ``JP Z, a16``` runs. Need to look more into thos.

**Comment by wornwinter** [comment]
Just a quick correction. The table we look up the human readable opcode names in is wrong again lol.

It's not JP, should be

```[0x00002A05] 0xCB 0x37      SWAP A```

**Comment by wornwinter** [comment]
And I know the reason for the segfault. The emulator is trying to call the entry for CB37 in the opcode table, but because we haven't initialised the CB table with NULLs, it tries to jump into memory that isn't part of our program. Windows isn't happy about that aaaaaand segfault.

**Comment by Quaker762** [comment]
Ahh okay, wouldn't have even guessed that lol.
