### ISSUE TITLE
Tetris hang on credits

### ISSUE THREAD

**Issue by Quaker762** [wornwinter/DMGe#32]
It's hanging, but I think I know why, it seems that BC rolls back around to FF and gets stuck in an infinite loop of decrementing. Apart from that I have no idea haha. Here's what I think is happening:

[027c] - JR NZ, r8         - AF: 40 BC: 216 DE: 6550 HL: 9501 SP: cfff
[027a] - LD (HL-), A         - AF: 40 BC: 216 DE: 6550 HL: 9501 SP: cfff
[027b] - DEC B         - AF: 40 BC: 216 DE: 6550 HL: 9500 SP: cfff
[027c] - JR NZ, r8         - AF: 40 BC: 116 DE: 6550 HL: 9500 SP: cfff
[027a] - LD (HL-), A         - AF: 40 BC: 116 DE: 6550 HL: 9500 SP: cfff
[027b] - DEC B         - AF: 40 BC: 116 DE: 6550 HL: 94ff SP: cfff
[027c] - JR NZ, r8         - AF: c0 BC: 16 DE: 6550 HL: 94ff SP: cfff
[027e] - DEC C         - AF: c0 BC: 16 DE: 6550 HL: 94ff SP: cfff
[027f] - JR NZ, r8         - AF: 40 BC: 15 DE: 6550 HL: 94ff SP: cfff
[027a] - LD (HL-), A         - AF: 40 BC: 15 DE: 6550 HL: 94ff SP: cfff
[027b] - DEC B         - AF: 40 BC: 15 DE: 6550 HL: 94fe SP: cfff
[027c] - JR NZ, r8         - AF: 60 BC: ff15 DE: 6550 HL: 94fe SP: cfff <- B, what are you doing?!?!

**Comment by wornwinter** [comment]
Haha you're back?

I'll take a look at this tonight.

**Comment by Quaker762** [comment]
I thought you were the one that disappeared! Anyway I'm nearly free of year 12 so I thought I'd go over the emulator. I've tried a few different combinations of decrementing B with no success. Do you thibk the issue lies in the CPU or GPU?

**Comment by wornwinter** [comment]
I'm not 100% sure, but I'll take a look over it tonight and see if I can come up with an explanation.

**Comment by wornwinter** [comment]
I think the issue is that as B is an unsigned char, decrementing it must be causing it to loop around to 0xFF as it can't have a value lower than zero due to the lack of a sign bit. Try implementing a zero check, and if it's already zero, do nothing. That might work.

**Comment by Quaker762** [comment]
I tried before and it either screwed with the logo graphics or hung the the CPU (I'm not at my PC and about to go to sleep sorry haha). I also tried casting to to a regular int8 and it did the same thing. Pretty sure our problems lie in this opcode though, unless theres a mistake elsewhere writing funky data (I hope not)

**Comment by wornwinter** [comment]
I'll have to go investigate what the gameboy CPU would do in this case and try to emulate it accordingly, but there is no need to cast it to an signed integer IMO. Surely leaving it at zero and setting the zero flag. But I'll have to double check later.

**Comment by Quaker762** [comment]
Okay cool. Hopefully we can get some games running soon.

**Comment by Quaker762** [comment]
http://imgur.com/HDMaFlW

I think the problem lies here??

**Comment by wornwinter** [comment]
As promising a lead as any lol

**Comment by Quaker762** [comment]
Looks like the loop has been fixed! Here's where the problems were!
1. When we wrote the CPU core, I was checking for half carry and carry in wrong places (sorry..). To be honest, I'm not sure how it actually even got past the BIOS on boot....
In a decrement, for a example, the HC flag should be UNSET if the value & 0x0F is true BEFORE the decrement
2. The blocking of the write to 0xFF80 also seems to have fixed the zeroes being written all over the screen, probably because of some weird framebuffer writes or vblank interrupt crap.

I'll have to go over some more of the instructions, as they could be buggy, but for now, the emulator loads to the copyright screen of Tetris before hanging with no weird graphical artifacts! :)

**Comment by wornwinter** [comment]
That's great. Can you rebase with my changes last night and submit a pull request? 

Thanks!

**Comment by Quaker762** [comment]
![it sworking](https://cloud.githubusercontent.com/assets/4768900/11014475/3ac151ba-858b-11e5-95f6-5f94c7c23b5c.png)

Blast off!

**Comment by wornwinter** [comment]
Fantastic! Well done!
