### ISSUE TITLE
Tetris wrong values loaded into A from (HL)??

### ISSUE THREAD

**Issue by Quaker762** [wornwinter/DMGe#35]
This is going to be a tough one to debug... So far I've fixed a few instructions that were setting the flags register wrong and what not, however at address 0x6C53, it seems like the value being read from df91 is completely wrong (should be 76 but 2f is being read). If you load up no$gmb and set a breakpoint at that address you can see what I mean. Here's the trace from dmge

[Newtrace.docx](https://github.com/wornwinter/DMGe/files/29458/Newtrace.docx)

Usually something like this wouldn't be a problem, and no$gmb will continue to run properly if A is changed to 2f at that point (I assume the game has some type of correction to deal with something like this happening), however, after implementing all instructions, dmge sits for a bit, then jumps to the tetris game screen, dumps some chunk of the tileset (it's pretty funny lol) then executes an unknown instruction. 

Setting a breakpoint 0x6D2B (right before the game loads) shows that registers should have the following values:
AF: 0x0600
BC: 0x0014
DE: 0x8074
HL: 9xDF9A

dmge craps the bed and gives
AF: 0x0500
BC: 0x0014
DE: 0x0000
HL: 9xDF9A

I'm assuming there's an issue with an operation acting on A, but I find it weird that DE is completely cleared...

Nonetheless, I'll create a new pull request (when the old one is merged) and hopefully you can see where the issue lies (I'm completely stumped). We are literally so close to getting Tetris to run lol, it hurts haha

**Comment by Quaker762** [comment]
Okay I think I've narrowed it down. There are definitely some wrong values being written to addresses (I'm not sure where..). It's strange because all the operations seem to be doing everything correctly, but the values from the HL pointer are just completely off and it screws everything else up...

**Comment by wornwinter** [comment]
Could this be down to missing interrupts?

**Comment by Quaker762** [comment]
I'm not 100% sure, I thought that could be the case. no$ doesn't seem to specify any interrupts at the point. It seems to be values written (I forced a write to 0xDF91 as 0x72) and it read the proper values so it's not that. I thought it could be some weird addition/messed up operations, but everything operates 100% normally, flags are set and all acts predictable. It's probably something really really tiny that's causing a massive downwards spiral ahaha.

**Comment by Quaker762** [comment]
![pcaddr](https://cloud.githubusercontent.com/assets/4768900/11020011/b31cba0c-8665-11e5-88ee-5d1c7b77e30a.png)

Here are the PC values that are writing to 0xDF91

**Comment by wornwinter** [comment]
I think we should implement some more of the missing opcodes before working much on this.

**Comment by Quaker762** [comment]
Yeah sounds like a good idea. Sorry about spending so much time trying to debug it haha

**Comment by wornwinter** [comment]
I've implemented more opcodes. Tetris just hangs now, no more unknown opcodes. If you get the chance can you double check that our implemented opcodes are setting the flags correctly? That might get us somewhere.

I've a funny feeling that it'll be waiting for input though. Although just skimming DMGCPU, it's easy to see that there are issues with the flags at a glance.

**Comment by Quaker762** [comment]
Yep sure thing on it now. I think some of the flag checks are wrong so I'll change em. Have you had the weird crash yet? You have to wait for it to hang for a bit, but it should dump a heap of crap to the screen.

**Comment by Quaker762** [comment]
By the way it says you upgraded Boost and wxWidgets?? Which version was it? I'm getting a whole heap of Undefined references on link.

**Comment by wornwinter** [comment]
wxwidgets 3.01 and boost 1.59.

Sorry about that lol

**Comment by Quaker762** [comment]
@wornwinter Nope my fault... I have a GCC 4.7 and GCC 4.8 compiled versions... Apparently code::blocks is using GCC 4.7 hahaha.

**Comment by wornwinter** [comment]
Haha that happened to me too. MinGW doesn't like libraries built with
different versions.
