### ISSUE TITLE
Library versions for Readme.md

### ISSUE THREAD

**Issue by Quaker762** [wornwinter/DMGe#6]
I forgot what version of wxWidgets we should be using. I compiled one myself, however the *wxUSE_UNICODE=1* instruction is giving me undefined references everywhere.

Could you possibly add libraries and compiler flags (for wxWidgets) to the Readme?

**Comment by wornwinter** [comment]
It'll build with the most recent version of wxWidgets, so I'd say we should leave the library versions for now. If we find that a new release breaks it, then I think we should look at that.

You need to have wxUSE_UNICODE=0 depending on how you built it. If you built it with unicode support that wouldn't be an issue. Personally I didn't, no real reason, just seemed like the way it was recommended to build it.

I'll have a look at the readme anyways and see.
