### ISSUE TITLE
DMG_opcodes doesn't match up with opcodes.

### ISSUE THREAD

**Issue by wornwinter** [wornwinter/DMGe#7]
Just something I noticed today.

For example, looking up 0xFE in the table returns the text for "RST 38H" but it's actually "CP d8".

**Comment by wornwinter** [comment]
Not a major issue, but just thought I'd make you aware of it lol.

**Comment by Quaker762** [comment]
Yes I found this the other day. Unfortunately going to have to comb through every opcode in the table and find which one is missing....

**Comment by Quaker762** [comment]
Found it. Can't hide from me, *LD (HL), D* hahahaha

**Comment by wornwinter** [comment]
Haha that simple. Good work :).

Going to have a look at your latest pull request in a minute.
