### ISSUE TITLE
Graphics Scaling

### ISSUE THREAD

**Issue by Quaker762** [wornwinter/DMGe#9]
I've got graphics scaling working, didn't know if you wanted me to commit it, as it's basically multiplying everything by a preprocessor macro (and pretty ugly...)

**Comment by Quaker762** [comment]
Just thought I'd tell you how it works
-*Everything* is scaled by a hard factor of 2, including Pixel functions and Pixel buffer
-The OpenGL viewport is also scaled and OpenGL is sent a *glScalef* command, just so it knows everything is bigger.

So yeah, pretty ugly, but it works I guess.

I'm guessing the scale factors will be hard coded, as ratios depending on window size could go quite wrong and look weird.

**Comment by wornwinter** [comment]
I'll commit it and test, then if it works well great, if not we could just revert. We could probably do cleaner methods of scaling, as we're just drawing to a quad, but should do in the meantime :)

**Comment by Quaker762** [comment]
Okay, I was going to work on a scaling function that's a bit cleaner lol.
Yeah drawing to a quad makes life a lot easier lol. I just made it a little bit cleaner by not scaling the pixel buffer (just the viewport and panel) and it seems to work just as well. I'll get working on an actual scale fucntion in the canvas classs now.

**Comment by wornwinter** [comment]
I had to change quite a bit of the scaling. The pixel buffer wasn't being drawn correctly. Made a commit already to cover it, but it's great, thanks :)

**Comment by wornwinter** [comment]
I'd say this can be closed for now. I feel it works just fine.
